### ISSUE TITLE
Include link to game

### ISSUE THREAD

**Issue by bkeepers** [Zarkonnen/Martian-Immigration-Nightmare#2]
It looks like the game is available at https://zarkonnen.github.io/Martian-Immigration-Nightmare/. Want to add it as the homepage in the repository settings to make it easier to find?

**Comment by Zarkonnen** [comment]
Good point, thank you. I've linked to https://zarkonnen.itch.io/martian-immigration-nightmare because that's the, like, primary point the game is published. :+1:
